config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :treatments
  resources :categories
  resources :therapists

  get 'homes/index'
  get 'homes/about'
  get 'homes/services'
  get 'homes/counselling'
  get 'homes/faq'
  get 'homes/team'
  get 'homes/gallery'
  get 'homes/contacts'
  
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/therapist.rb
class Therapist < ApplicationRecord
  has_many :appointments
end

app/controllers/therapists_controller.rb
class TherapistsController < ApplicationController
  before_action :set_therapist, only: [:show, :edit, :update, :destroy]

  # GET /therapists
  # GET /therapists.json
  def index
    @therapists = Therapist.all
  end

  # GET /therapists/1
  # GET /therapists/1.json
  def show
  end

  # GET /therapists/new
  def new
    @therapist = Therapist.new
  end

  # GET /therapists/1/edit
  def edit
  end

  # POST /therapists
  # POST /therapists.json
  def create
    @therapist = Therapist.new(therapist_params)

    respond_to do |format|
      if @therapist.save
        format.html { redirect_to @therapist, notice: 'Therapist was successfully created.' }
        format.json { render :show, status: :created, location: @therapist }
      else
        format.html { render :new }
        format.json { render json: @therapist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /therapists/1
  # PATCH/PUT /therapists/1.json
  def update
    respond_to do |format|
      if @therapist.update(therapist_params)
        format.html { redirect_to @therapist, notice: 'Therapist was successfully updated.' }
        format.json { render :show, status: :ok, location: @therapist }
      else
        format.html { render :edit }
        format.json { render json: @therapist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /therapists/1
  # DELETE /therapists/1.json
  def destroy
    @therapist.destroy
    respond_to do |format|
      format.html { redirect_to therapists_url, notice: 'Therapist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_therapist
      @therapist = Therapist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def therapist_params
      params.require(:therapist).permit(:name, :mobile, :address)
    end
end

app/helpers/therapists_helper.rb
module TherapistsHelper
end

app/views/therapists/_form.html.erb
<%= form_with(model: therapist, local: true) do |form| %>
  <% if therapist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(therapist.errors.count, "error") %> prohibited this therapist from being saved:</h2>

      <ul>
      <% therapist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :therapist_name %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id: :therapist_mobile %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :therapist_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/therapists/edit.html.erb
<h1>Editing Therapist</h1>

<%= render 'form', therapist: @therapist %>

<%= link_to 'Show', @therapist %> |
<%= link_to 'Back', therapists_path %>

app/views/therapists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Therapists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @therapists.each do |therapist| %>
      <tr>
        <td><%= therapist.name %></td>
        <td><%= therapist.mobile %></td>
        <td><%= therapist.address %></td>
        <td><%= link_to 'Show', therapist %></td>
        <td><%= link_to 'Edit', edit_therapist_path(therapist) %></td>
        <td><%= link_to 'Destroy', therapist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Therapist', new_therapist_path %>

app/views/therapists/new.html.erb
<h1>New Therapist</h1>

<%= render 'form', therapist: @therapist %>

<%= link_to 'Back', therapists_path %>

app/views/therapists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @therapist.name %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @therapist.mobile %>
</p>

<p>
  <strong>Address:</strong>
  <%= @therapist.address %>
</p>

<%= link_to 'Edit', edit_therapist_path(@therapist) %> |
<%= link_to 'Back', therapists_path %>