config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :appointments
  resources :treatments
  resources :categories
  resources :therapists

  get 'homes/index'
  get 'homes/about'
  get 'homes/services'
  get 'homes/counselling'
  get 'homes/faq'
  get 'homes/team'
  get 'homes/gallery'
  get 'homes/contacts'
  
  root to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end

  def about
  end

  def services
  end

  def counselling
  end

  def appointment
  end

  def faq
  end

  def team
  end

  def gallery
  end

  def contacts
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/contacts.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<title>Optima | Contacts</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="format-detection" content="telephone=no" />

	<!-- Favicon -->
	<link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
	<link rel="apple-touch-icon" href="favicon.ico" />

	<link rel="apple-touch-icon" sizes="57x57" href="../img/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="../img/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="../img/favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="../img/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="../img/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="../img/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="../img/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="../img/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="../img/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192" href="../img/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="../img/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="../img/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="../img/favicon/favicon-16x16.png">
	<link rel="manifest" href="/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">

	<!-- Bootstrap v3.3.7 -->
	<link rel="stylesheet" href="../css/bootstrap.min.css">

	<!-- Font Awesome 4.7.0 -->
	<link rel="stylesheet" href="../css/font-awesome.min.css">

	<!-- Main style -->
	<link rel="stylesheet" href="../css/style.css">

</head>

<body>

	<!--[if lt IE 9]>
			<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
		<![endif]-->

	<div class="wrapp-content">

		<!-- Header -->
		<header class="wrapp-header">
			<div class="info-block-01">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<p class="visit-time">Visit Us Daily from 8.00 AM to 6.00 PM</p>
							<div class="info-block-01__box-01">
								<p class="address-info">Bengaluru, Karnataka</p>
								<a class="email-info" href="mailto:turninglife360x@gmail.com">turninglife360x@gmail.com</a>
								<a class="free-consultation-link" href="#">Request a Consultation Now</a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="header-box-01">
				<div class="container">
					<div class="row">
						<div class="col-sm-4 col-md-4 col-lg-4 text-xs-center">
							<a href="./" class="logo">
								<img src="../img/logo.png" alt="">
							</a>
						</div>
						<div class="col-sm-8 col-md-8 col-lg-8 text-xs-center text-right">
							<p class="phone-info">
								<span>Call:</span> 94496 16912</p>
							<%= link_to "MAKE AN APPOINTMENT", appointments_path, class: "btn-app" %>
						</div>
					</div>
				</div>
			</div>

			<!-- Main navigation -->
			<div class="header-box-02">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="main-nav">
								<div class="main-nav__btn">
									<div class="icon-left"></div>
									<div class="icon-right"></div>
								</div>
								<ul class="main-nav__list">
									<li>
										<%# <a href="index.html">Home</a> %>
										<%= link_to "Home", root_path %>
									</li>
									<li>
										<%# <a href="about_us.html">About</a> %>
										<%= link_to "Counselling", homes_counselling_path %>
									</li>
									<li>
										<%# <a href="about_us.html">About</a> %>
										<%= link_to "Gallery", homes_gallery_url %>
									</li>
									<li>
										<%# <a href="services.html">Services</a> %>
										<%= link_to "Services", homes_services_path %>
									</li>
									<li>
										<%# <a href="about_us.html">About</a> %>
										<%= link_to "Team", homes_team_path %>
									</li>
									<li>
										<%# <a href="about_us.html">About</a> %>
										<%= link_to "About", homes_about_path %>
									</li>	
									<li>
										<%# <a href="about_us.html">About</a> %>
										<%= link_to "FAQ", homes_faq_path %>
									</li>			
									<li class="active">
										<%# <a href="contacts.html">Contacts</a> %>
										<%= link_to "Contacts", homes_contacts_path %>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>

		<!-- Content -->
		<main class="content-row">
			<div class="page-title-wrapp">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<h2 class="page-title-01">Contacts</h2>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
							<ul class="breadcrumbs">
								<li class="active">
									<a href="index.html">Home</a>
								</li>
								<li>Contacts</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="content-box-01 pad-bt-90">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-lg-6">
							<div class="contacts-map-wrapp">
								<div class="contacts_map">
									<div id="map-canvas"></div>
								</div>
							</div>
						</div>
						<div class="col-md-6 col-lg-6">
							<div class="contacts-block-wrapp">
								<h6 class="subtitle-04">Get in touch</h6>
								<h3 class="title-02">Find Us on a
									<span>Map</span>
								</h3>
								<div class="contacts-block-01">
									<p>We have worls-class, flexible support via live chat, email and phone. We guarantee that you’ll be able to have any issue resolved within 24 hours. You van contact support immediately here.</p>
								</div>
								<p class="contact-location">455 Wallstreet St., NY, USA</p>
								<a class="contact-mail" href="maito:companyname@gmail.com">companyname@gmail.com</a>
								<p class="contact-phone">Call:
									<span>800 326 9160</span>
								</p>
								<div class="reply-form">
									<div role="form" class="form-in-wrapp" id="form-in-wrapp-f1053-p976-o1" lang="en-US" dir="ltr">
										<div class="screen-reader-response"></div>
										<div id="note"></div>
										<div id="fields">
											<form id="ajax-contact-form" action="javascript:void(0);" method="post" novalidate="novalidate" class="reply-form__form">
												<div class="reply-form__box-01 name">
													<input class="reply-form__name form-in-wrapp-validates-as-required" type="text" name="name" aria-required="true" aria-invalid="false" placeholder="Name *">
												</div>
												<div class="reply-form__box-02 your-email">
													<input class="reply-form__email form-in-wrapp-validates-as-required form-in-wrapp-validates-as-email" type="email" name="email" aria-required="true" aria-invalid="false" placeholder="Email *">
												</div>
												<div class="reply-form__box-03 your-message">
													<textarea class="reply-form__message" name="message" aria-invalid="false" cols="30" rows="10" placeholder="Message..."></textarea>
												</div>
												<div class="reply-form__box-04">
													<button class="btn-01" type="submit">Send message</button>
												</div>
											</form>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</main>

		<!-- Footer -->
		<footer class="wrapp-footer">
			<div class="footer-box-01">
				<div class="container">
					<div class="row">
						<div class="col-sm-3 col-md-3 col-lg-3">
							<a href="./" class="footer-logo">
								<img src="../img/logo.png" alt="">
							</a>
							<div class="widget widget-text">
								<p>Our clinic largest private mental health partnership, with a carefully selected nationwide team of Psychiatrists.</p>
								<ul class="social-list-01">
									<li>
										<a href="#">
											<i class="fa fa-facebook" aria-hidden="true"></i>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-twitter" aria-hidden="true"></i>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-instagram" aria-hidden="true"></i>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-google-plus" aria-hidden="true"></i>
										</a>
									</li>
								</ul>
							</div>
						</div>
						<div class="col-sm-3 col-md-3 col-lg-3">
							<div class="widget widget-contacts">
								<h3 class="widget-title">Our Head Clinick</h3>
								<ul class="widget-contacts__list">
									<li>455 Wallstreet St., New York, VA 12364 United States of America</li>
									<li>
										<a class="contacts-email" href="maito:companyname@gmail.com">companyname@gmail.com</a>
									</li>
									<li>826 696 8370</li>
									<li>
										<p class="work-time">
											We Work for You Every Day from
											<span>8.00 AM</span> to
											<span>6.00 PM</span>
										</p>
									</li>
								</ul>
							</div>
						</div>
						<div class="col-sm-3 col-md-3 col-lg-3">
							<div class="widget widget-latest-news">
								<h3 class="widget-title">Our Latest News</h3>
								<ul class="widget-latest-news__list">
									<li>
										<h4 class="latest-news-title">
											<a href="#">Am i Depressed? 6 Signs You Should Know About</a>
										</h4>
										<p class="latest-news-date">25 September, 2017</p>
									</li>
									<li>
										<h4 class="latest-news-title">
											<a href="#">Anxiety Disorder: Which Therapy is Right for Me</a>
										</h4>
										<p class="latest-news-date">25 September, 2017</p>
									</li>
								</ul>
							</div>
						</div>
						<div class="col-sm-3 col-md-3 col-lg-3">
							<div class="widget widget-quick-links">
								<h3 class="widget-title">Quick Links</h3>
								<ul class="widget-quick-links__list">
									<li>
										<a href="#">Home</a>
									</li>
									<li>
										<a href="#">About</a>
									</li>
									<li>
										<a href="#">Services</a>
									</li>
									<li>
										<a href="#">News</a>
									</li>
									<li>
										<a href="#">Gallery</a>
									</li>
									<li>
										<a href="#">Contacts</a>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copy-footer-01">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<p class="copy-footer-01__text">&copy; 2017 OPTIMA. All rights reserved.</p>
						</div>
					</div>
				</div>
			</div>
			<a href="#" class="back2top" title="Back to Top">Back to Top</a>
		</footer>

	</div>

	<!-- JQuery v3.3.1 -->
	<script src="../js/jquery/jquery-3.3.1.min.js"></script>

	<!-- Main navigation sticky -->
	<script src="../js/plugins/jquery.sticky.min.js"></script>

	<!-- SuperFish v1.7.9 -->
	<script src="../js/plugins/jquery.superfish.min.js"></script>

	<!-- Google maps -->
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNm8iTBBSJr4h7dXOwqvw_8AbWIpw_sMo"></script>

	<!-- Main script -->
	<script src="../js/main.js"></script>

</body>

</html>